@host=https://localhost:7002

@adminId=2150E333-8FDC-42A3-9474-1A3956D46DE8

POST {{host}}/subscriptions
Content-Type: application/json

{
    "Subscriptiontype": "Free",
    "AdminId": "{{adminId}}"
}