@host=http://localhost:5238

@adminId=123e4567-e89b-12d3-a456-426614174000

POST {{host}}/api/subscriptions
Content-Type: application/json

{
    "Subscriptiontype": "Free",
    "AdminId": "{{adminId}}"
}